rename gitea

diff --git a/latest b/latest
--- a/latest
+++ b/latest
@@ -8,11 +8,11 @@
 xrc http param ui
 xrc ui/lib/table gh/lib/resource
 
-xrc:inner:lib gitlab utils config current token user issue/main project/main project/member groups/main groups/member
+xrc:inner:lib gitea utils config current token user issue/main project/main project/member groups/main groups/member
 
-x log init gitlab
-___x_cmd_gitlab(){
-    param:subcmd ___x_cmd_gitlab        \
+x log init gitea
+___x_cmd_gitea(){
+    param:subcmd ___x_cmd_gitea        \
         user        "user"              \
         project     "project command"   \
         config      "save, load, which" \
@@ -24,8 +24,8 @@ ___x_cmd_gitlab(){
     param:subcmd:try
     param:run
 
-    ___x_cmd_gitlab _param_help_doc
-    gitlab_log warn "Subcmd Not Found."
+    ___x_cmd_gitea _param_help_doc
+    gitea_log warn "Subcmd Not Found."
     return 1
 }
 
@@ -33,35 +33,35 @@ ___x_cmd_gitlab(){
 ############################
 # Section 10: Instantiation
 ############################
-___x_cmd_gitlab_make(){
+___x_cmd_gitea_make(){
     param:void
 
-    local O="___x_cmd_gitlab_${1:?Provide client name by O environment}"
+    local O="___x_cmd_gitea_${1:?Provide client name by O environment}"
 
-    ___x_cmd_http make  'https://gitlab.com/api/v4'
+    ___x_cmd_http make  'https://gitea.com/api/v4'
     ___x_cmd_http header put type  "application/json;charset=utf-8"
 
     local token
-    token="$(___x_cmd_gitlab_config_get "oauth_token")"
+    token="$(___x_cmd_gitea_config_get "oauth_token")"
 
     if [ -n "$token" ]; then
         ___x_cmd_http header put "PRIVATE-TOKEN" "$token"
-        ___x_cmd_gitlab_current_owner 1>/dev/null || return 1
-        gitlab_log info "Hi $___X_CMD_GITLAB_DEFAULT_OWNER! You've successfully authenticated."
+        ___x_cmd_gitea_current_owner 1>/dev/null || return 1
+        gitea_log info "Hi $___X_CMD_gitea_DEFAULT_OWNER! You've successfully authenticated."
         return 0
     fi
 
     local info
     info=$(printf "\n%s %s \n%s" \
          "$(___x_cmd_ui yellow 'You need run command to add token:')" \
-         "$(___x_cmd_ui bold cyan "\`gitlab token <token>\`")" \
+         "$(___x_cmd_ui bold cyan "\`gitea token <token>\`")" \
          "$(___x_cmd_ui 'https://gitee.com/profile/personal_access_tokens')")
-    gitlab_log warn "Token is null.${info}"
+    gitea_log warn "Token is null.${info}"
 }
 
-if [ -z "$DO_NOT_INIT_GITLAB_DEFAULT" ]; then
-    ___x_cmd_gitlab_make "GITLAB_DEFAULT" && DO_NOT_INIT_GITLAB_DEFAULT="true"
+if [ -z "$DO_NOT_INIT_gitea_DEFAULT" ]; then
+    ___x_cmd_gitea_make "gitea_DEFAULT" && DO_NOT_INIT_gitea_DEFAULT="true"
 fi
 
-xrc setmain ___x_cmd_gitlab
+xrc setmain ___x_cmd_gitea
 
